# Generated by Django 3.0.2 on 2020-03-18 12:41

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True)),
                ('event', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('prize', models.CharField(blank=True, max_length=20)),
                ('team_size', models.CharField(blank=True, max_length=20)),
                ('venue', models.CharField(blank=True, max_length=50)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('about', models.CharField(blank=True, max_length=1500)),
                ('pdf', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('pdf', models.FileField(blank=True, upload_to='pdfs')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenor', models.CharField(max_length=100)),
                ('role1', models.CharField(max_length=40)),
                ('phone_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('co_convenor1', models.CharField(max_length=100)),
                ('role2', models.CharField(max_length=40)),
                ('phone_number2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('co_convenor2', models.CharField(blank=True, max_length=100)),
                ('role3', models.CharField(blank=True, max_length=40)),
                ('phone_number3', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('member1', models.CharField(max_length=100)),
                ('role4', models.CharField(max_length=40)),
                ('member2', models.CharField(max_length=100)),
                ('role5', models.CharField(max_length=40)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
