# Generated by Django 3.0.2 on 2020-02-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Participants',
            new_name='Participant',
        ),
    ]
