# Generated by Django 3.0.2 on 2020-03-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200229_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pdf',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
