# Generated by Django 3.0.2 on 2020-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200302_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
