# Generated by Django 3.0.2 on 2020-03-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
