# Generated by Django 3.0.2 on 2020-02-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('link1', models.URLField(max_length=1000)),
                ('link2', models.URLField(max_length=1000)),
                ('link3', models.URLField(max_length=1000)),
                ('link4', models.URLField(max_length=1000)),
            ],
        ),
    ]
