# Generated by Django 3.0.2 on 2020-02-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='link4',
            new_name='dribble',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='link1',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='link2',
            new_name='linkedIn',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='link3',
            new_name='twitter',
        ),
    ]
