# Generated by Django 3.0.2 on 2020-02-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200218_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='team-profilepics'),
        ),
        migrations.AlterField(
            model_name='team',
            name='dribble',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='github',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedIn',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
