# Generated by Django 3.0.2 on 2020-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
